apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true

  - name: Mikofai DB
    uid: mikofai_pg
    type: postgres
    access: proxy
    url: db:5432
    user: ${POSTGRES_USER}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: true
